
name: Script docker create and push


on:
  pull_request:
    branches:
      - main
      - Desarrollo
    types: [closed]


jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          
        run: 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Docker build
        run: |
          docker build ./docker -t tiagopereyra/helloWorld:dev
          
      - name: Docker push
        run: |
          docker push tiagopereyra/helloWorld:dev
