
name: Script docker create and push


on:
  pull_request:
    branches:
      - main
      - Desarrollo
    types: [closed]


jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          
        run: 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./docker
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/hello-world:${{ steps.extract_branch.outputs.branch }}
            docker.pkg.github.com/${{ github.repository }}/hello-world:${{ steps.extract_branch.outputs.branch }}
