name: test  

on:
  pull_request:
    types: [opened]
    
jobs: 
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: test
      uses: actions/setup-node@v3
      with:
        node-version: "12.x"
    - run: npm install
    - run: npm test
 
  
