name: test  

on:
  pull_request:
    branches:
     -main
     -desarrollo
    
jobs: 
 run-tests:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Cypress run
    uses: cypress-io/github-actions@v2
    with: 
      build: npm run build
      start: npm start
  - name: Jest run
    run: npm test
 
  
